## Configuration Parameters
model_path: './model_data/yolo_weights.h5'
anchors_path: './model_data/yolo_anchors.txt'
classes_path: './model_data/voc_classes.txt'
annotation_path: './model_data/voc_annotation.txt'
gpu_num: 1
thresh_score: 0.3
thresh_iou: 0.45


## I/O Configuration
image_path: './test_data/img2.jpg'
video_path: ''
log_dir: './logs/'
